name: "pint"
run-name: "check format to changed files"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: |
          composer install
      - name: run lint
        run: |
          ./vendor/bin/pint -v
  merge_to_main:
    name: Merge to Main
    runs-on: ubuntu-latest
    needs: lint # Waits for the 'lint' job to finish successfully
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
