name: Laravel Tests

on: [push, pull_request]

jobs:
  tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use node
      uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: script/validate-data/package-lock.json
    - name: Start Sail
      run: |
        sudo ./vendor/bin/sail up -d

    - name: Install dependencies
      run: |
        sudo ./vendor/bin/sail composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate application key
      run: |
        sudo ./vendor/bin/sail artisan key:generate

    - name: Run tests
      run: |
        sudo ./vendor/bin/pint test
    - name: Run edit
      run: |
        sudo ./vendor/bin/pint -v
