name: Laravel Tests

on: [push, pull_request]

jobs:
  tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Sail
      run: |
        sudo ./vendor/bin/sail up -d

    - name: Install dependencies
      run: |
        sudo ./vendor/bin/sail composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate application key
      run: |
        sudo ./vendor/bin/sail artisan key:generate

    - name: Run tests
      run: |
        sudo ./vendor/bin/pint test
    - name: Run edit
      run: |
        sudo ./vendor/bin/pint -v
