name: "pint"
run-name: "check format to changed files"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: |
          composer install
      - name: run lint
        run: |
          ./vendor/bin/pint -v
  merge_to_main:
    name: Merge to Main
    runs-on: ubuntu-latest
    needs: lint # Waits for the 'lint' job to finish successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git config --global user.email "lanlh@zigexn.vn"
          git config --global user.name "lanlh2023"
          git checkout main
          git merge ${{ github.sha }}
          git push origin main
