name: Laravel Pint
run-name: "check format to changed files"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl git

      - name: Clone Sail repository
        run: git clone https://github.com/laravel/sail.git ./.sail
      - name: Run Laravel Pint
        run: |
          ./vendor/bin/sail up -d
          ./vendor/bin/pint -v
