name: "pint"
run-name: "check format to changed files"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: |
          composer install
      - name: run lint
        run: |
          ./vendor/bin/pint -v
