name: Laravel Pint
run-name: "check format to changed files"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sail
        uses: akondas/sail@v1.2.1
      - name: Run Laravel Pint
        run: |
          ./vendor/bin/sail up -d
          ./vendor/bin/pint
