name: "pint"
run-name: "check format to changed files"
on:
  push:
    branches:
      - "main"
      - "feature/*"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: |
          composer install
      - name: run lint
        run: |
          ./vendor/bin/pint -v
  merge-branch:
    name: Merge to Main
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@master
      - name: Merge by labeled
        uses: devmasx/merge-branch@master
        with:
          label_name: 'merged in main'
          target_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
