name: "Build"

on:
  pull_request:
    branches: # PRs to the following branches will trigger the workflow
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - 'app/Console/Commands/SendMailCron.php'
      - name: backend tests
      if: steps.filter.outputs.backend == 'true'
      run: |
        echo 'changed'
