name: "Build"

on:
  pull_request:
    branches:  # Use square brackets for branches list
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Only one checkout step needed
      - name: Filter backend changes
        id: filter  # Consistent naming with step name
        uses: dorny/paths-filter@v3
        with:
          filters: |  # Indentation for readability
            backend:
              - 'app/Console/Commands/SendMailCron.php'
      - name: Run backend tests (if changed)
        if: steps.filter.outputs.backend  # Use direct access to output
        run: |
          echo 'changed'
