name: Check File Changes

on:
  push: branches: [ main ]
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed_files
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            git diff --name-only -r HEAD^1 HEAD
          else
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
          fi

      - name: Print changed files
        run: echo "Changed files:" && cat << EOF
        $(echo ${{ steps.changed_files.outputs.changed_files }})
        EOF

      - name: Show diff for changed files (optional)
        run: |
          for file in $(echo ${{ steps.changed_files.outputs.changed_files }}); do
            git diff $file
          done
        if: ${{ github.event_name == 'pull_request' }}
