name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if files changed
        run: |
          git diff --name-only HEAD HEAD~1 | grep -q .

      - name: Run command A if files changed
        if: ${{ steps.check-if-files-changed.outputs.files-changed }}
        run: |
          echo 'changed'

      - name: Deploy to staging environment
        if: ${{ steps.check-if-files-changed.outputs.files-changed }}
