name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: |
          composer install

  self-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      id: filter
      with:
        filters: '.github/filters.yml'
    - name: filter-test
      if: steps.filter.outputs.any != 'true' || steps.filter.outputs.error == 'true'
      run: |
          ./vendor/bin/pint -v
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: PHP Linting (Pint)
        skip_fetch: true
