name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: |
          composer install

  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files (push event)
        id: check_changes
        if: github.event_name == 'push'
        run: |
          if git diff --name-only ${{ github.base_ref}} ${{ github.sha }} | grep -E "SendMailCron"; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi
      - name: Run update_mail if UpdateBodyMail changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          bin/cake update_mail
      - name: Run update_mail if UpdateBodyMail No changed
        if: steps.check_changes.outputs.changed == 'false'
        run: |
          echo "No change"
