name: "Build"

on:
  pull_request:
    branches: # PRs to the following branches will trigger the workflow
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'app/Console/Commands/SendMailCron.php'
        - name: backend tests
        if: steps.filter.outputs.backend == 'true'
        run: |
          echo 'changed'
